# Generated by Django 5.0.6 on 2024-06-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latitude',
            new_name='LatitudeModel',
        ),
        migrations.RenameModel(
            old_name='Longitude',
            new_name='LongitudeModel',
        ),
    ]
