# Generated by Django 5.0.6 on 2024-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_latitude_latitudemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('occurrence_time', models.DateTimeField()),
                ('event_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Error', 'Error'), ('Info', 'Info'), ('Warning', 'Warning')], default='Info', max_length=10)),
            ],
        ),
    ]
