# Generated by Django 5.0.6 on 2024-06-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_populate_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='latitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_ln', to='location.latitudemodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='longitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_lt', to='location.longitudemodel'),
        ),
    ]
